Product business
MishkaTeam/UniBazzar pull request #3
Opened 2024-11-22 16:31 UTC by MohammadSadeghAb

A UnitTest was created in the [ProductImages] folder named ProductImageTest.cs

A UnitTest was created in the [ProductPriceList] folder named ProductPriceListTest.cs

2024-11-23 20:43 UTC, Husseinbeygi requested changes

2024-11-23 20:43 UTC, Husseinbeygi commented on src/Core/Domain/Aggregates/ProductFeatures/ProductFeature.cs
> +	private static string FixString(string value)
ما این متد رو توی Framework,DataTypes.string داریم از اون استفاده کن

2024-11-23 20:43 UTC, Husseinbeygi commented on tests/Domain.UnitTests/Aggregates/ProductFeatures/ProductFeaturesTests.cs
> +	public void Create_WithWhiteSpaceKayAndValue_ShouldRemoveSpaces()
این تست رو بنویس برای Framework DataTypes 
داخل پوشه تست یک پروژه دیگه بساز به هم اسم خود Class Library که بشه متوجه شد مال کدوم بخش پروژه هستش و بعدش این تست رو بنویس برای اون

2024-11-24 18:33 UTC, SajjadDoosty commented
Changes applied! plz check it.

2024-11-25 17:24 UTC, Husseinbeygi approved these changes

2024-11-25 17:24 UTC, merged