feat: Add Class Customer
MishkaTeam/UniBazzar pull request #4
Opened 2024-11-22 17:45 UTC by Angelsky051

2024-11-22 17:52 UTC, Husseinbeygi commented
یک متد بزن به اسم Create و برو ببین توی کلاس Unit چیکار کردم و همینجا همون کار رو بکن

2024-11-22 17:57 UTC, Husseinbeygi requested changes

2024-11-22 17:57 UTC, Husseinbeygi commented on src/Persistence/Persistence/Aggregates/Customers/Customer.cs
> +        [MaxLength(50)]
تمام اینا رو پاکن و روی کلاست Attribute نزار اینا رو توی جای دیگه ای هندل میکنیم

2024-11-22 17:57 UTC, Husseinbeygi commented on src/Persistence/Persistence/Aggregates/Customers/Customer.cs
> +        public string Password { get; set; } = "";
این --- = "" --- رو از جلوی پراپرتی های کلاست بردار

2024-11-22 17:57 UTC, Husseinbeygi commented on src/Persistence/Persistence/Aggregates/Customers/Customer.cs
> +    public class Customer
کلاست از Entity ارث بری نکرده

2024-11-22 17:57 UTC, Husseinbeygi commented on src/Persistence/Persistence/Aggregates/Customers/Customer.cs
> +﻿using System;
اینا همه اضافه اس

2024-11-22 17:57 UTC, Husseinbeygi commented on src/Persistence/Persistence/Aggregates/Customers/Customer.cs
> +        public string ShippingAddress { get; set; } = "";
واسه این یک کلاس دیگه بساز و توی اون پراپرتی هایی مثال کشور - استان - شهر - آدرس - پلاک و کد پستی رو بزار

2024-11-22 17:57 UTC, Husseinbeygi commented on src/Persistence/Persistence/Aggregates/Customers/Customer.cs
> +namespace Persistence.Aggregates.Customers
از فایل اسکوپ نیم اسپیس ها استفاده کن ( توی ویژوال استادیو یک ; بزاری جلوی اسمش خودش برات درست میکنه)

2024-11-24 13:11 UTC, Angelsky051 commented on src/Persistence/Persistence/Aggregates/Customers/Customer.cs
> +        public string ShippingAddress { get; set; } = "";
منظور خود شاپینگ آدرس و بکنم یک کلاس و توش پراپرتی تعریف کنم دیگ؟
Public class shippingaddress
{ Public string city{set;get;}
}

2024-11-26 18:03 UTC, Husseinbeygi commented
یک متد بزن به اسم  AddShippingAddress که ورودی مشخصات اون ادرس رو بگیره و به اون لیست داخل کلاس اضافه کنه

2024-11-26 18:13 UTC, Husseinbeygi requested changes

2024-11-26 18:13 UTC, Husseinbeygi commented on src/Persistence/Persistence/Aggregates/Customers/ShippingAddress.cs
> +namespace Persistence.Aggregates.Customers
File Scope بشه

2024-11-26 18:13 UTC, Husseinbeygi commented on src/Persistence/Persistence/Aggregates/Customers/Customer.cs
> +        public ShippingAddress fullAddress { get; set; }
اینو لیست کن
یک نفر ممکنه چندتا ادرس داشته باشه

2024-12-03 15:48 UTC, Husseinbeygi approved these changes

2024-12-03 15:50 UTC, merged